<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php

$_currency =  Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
    
$slides = $this->getSlides();
if ($slides) {
?>
    <style>
        .cms-home .wrapper .page .header-wideimage {
            height: 0;
        }
    </style>
    <section class="slider homepage-slider">
        <div class="fullwidthbanner-container">
        <div class="fullwidthbanner">
        <ul>
            <?php foreach ($slides as $item) {

//                var_dump($item);
//                exit();?>
                <li data-transition="papercut" data-slotamount="15" data-masterspeed="300" data-delay="9400" data-thumb="<?php echo $this->getSkinUrl('revolution_slider/images/thumbs/thumb2.jpg')?>">
                    <img class="homepage-slide-cover" src="<?php echo Mage::helper('headerslider')->getImageFileHttp().'/'.$item['image_filename'] ?>" />


                    <?php
                        echo $processor->filter($item['content']);
                        $i = 0;
                        foreach ($item['products'] as $_product):
                    ?>
                            <div class="caption lft ltb"
                                 data-x="500"
                                 data-y="0"
                                 data-speed="600"
                                 data-start="<?php echo 1100+($i*2500); ?>"
                                 data-easing="easeOutExpo" data-end="<?php echo 3100+($i*2500); ?>" data-endspeed="300" data-endeasing="easeInSine" ><a href="<?php echo $_product->getProductUrl() ?>"><img class="header-slider-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image',$_image)->keepFrame(false)->resize(null,502); ?>" /></a></div>

                            <div class="caption modern_big_redbg sft stb"
                                 data-x="620"
                                 data-y="290"
                                 data-speed="300"
                                 data-start="<?php echo 1400+($i*2500); ?>"
                                 data-easing="easeOutExpo" data-end="<?php echo 3300+($i*2500); ?>" data-endspeed="300" data-endeasing="easeInSine" ><?php echo $_product->getName();?></div>

                            <div class="caption big_black sfb stb"
                                 data-x="620"
                                 data-y="320"
                                 data-speed="300"
                                 data-start="<?php echo 1700+($i*2500); ?>"
                                 data-easing="easeOutExpo" data-end="<?php echo 3200+($i*2500); ?>" data-endspeed="300" data-endeasing="easeInSine" ><?php echo $_currency; ?><?php echo number_format($_product->getFinalPrice(),2);?></div>
                    <?php
                        $i++;
                        endforeach;
                    ?>
                </li>
            <?php } ?>

        </ul>

        <div class="tp-bannertimer tp-bottom"></div>
        </div>
        </div>

    </section>

<?php } ?>


<!--
##############################
 - ACTIVATE THE BANNER HERE -
##############################
-->
<script type="text/javascript">

    var tpj=jQuery;
    tpj.noConflict();

    tpj(document).ready(function() {

        if (tpj.fn.cssOriginal!=undefined)
            tpj.fn.css = tpj.fn.cssOriginal;

        var api = tpj('.fullwidthbanner').revolution(
            {
                delay:9000,
                startwidth:960,
                startheight:500,

                onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off

                thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                thumbHeight:50,
                thumbAmount:3,

                hideThumbs:0,
                navigationType:"bullet",				// bullet, thumb, none
                navigationArrows:"solo",				// nexttobullets, solo (old name verticalcentered), none

                navigationStyle:"round",				// round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


                navigationHAlign:"center",				// Vertical Align top,center,bottom
                navigationVAlign:"bottom",					// Horizontal Align left,center,right
                navigationHOffset:0,
                navigationVOffset:20,

                soloArrowLeftHalign:"left",
                soloArrowLeftValign:"center",
                soloArrowLeftHOffset:20,
                soloArrowLeftVOffset:0,

                soloArrowRightHalign:"right",
                soloArrowRightValign:"center",
                soloArrowRightHOffset:20,
                soloArrowRightVOffset:0,

                touchenabled:"on",						// Enable Swipe Function : on/off


                stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
                stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic

                hideCaptionAtLimit:0,					// It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
                hideAllCaptionAtLilmit:0,				// Hide all The Captions if Width of Browser is less then this value
                hideSliderAtLimit:0,					// Hide the whole slider, and stop also functions if Width of Browser is less than this value


                fullWidth:"on",

                shadow:0								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

            });


        // TO HIDE THE ARROWS SEPERATLY FROM THE BULLETS, SOME TRICK HERE:
        // YOU CAN REMOVE IT FROM HERE TILL THE END OF THIS SECTION IF YOU DONT NEED THIS !
        api.bind("revolution.slide.onloaded",function (e) {


            jQuery('.tparrows').each(function() {
                var arrows=jQuery(this);

                var timer = setInterval(function() {

                    if (arrows.css('opacity') == 1 && !jQuery('.tp-simpleresponsive').hasClass("mouseisover"))
                        arrows.fadeOut(300);
                },3000);
            })

            jQuery('.tp-simpleresponsive, .tparrows').hover(function() {
                jQuery('.tp-simpleresponsive').addClass("mouseisover");
                jQuery('body').find('.tparrows').each(function() {
                    jQuery(this).fadeIn(300);
                });
            }, function() {
                if (!jQuery(this).hasClass("tparrows"))
                    jQuery('.tp-simpleresponsive').removeClass("mouseisover");
            })
        });
        // END OF THE SECTION, HIDE MY ARROWS SEPERATLY FROM THE BULLETS

    });

</script>