<?php
/**
 * Magento
 *
 * @category    design
 * @package     sixtyone_default
 * @copyright   Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 */
?>
<?php
/**
 * @see Mage_Reports_Block_Product_Viewed
 */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="widget widget-viewed">
    <section class="block-list">
        <header>
            <h2><?php echo $this->__('Recently Viewed') ?></h2>
        </header>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-images-list" id="widget-viewed-<?php echo $suffix; ?>">
            <?php foreach ($_products as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(76) ?>" width="76" height="76" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-viewed-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </section>
</div>
<?php endif; ?>
