<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php $collection = $this->getProductsCollection(); ?>
<?php if($collection->count()): ?>

    <?php if($this->getData('with_image')): ?>
        <div class="wideimage-wrapper sale-products">
            <div class="wideimage" style="background: transparent url(<?php echo Mage::getBaseUrl('media') . '/magazento_sixtyone/' . Mage::getStoreConfig('sixtyone/wideimage/wide_image2'); ?>) 50% 50%  no-repeat; background-size: cover;">
                <div class="container_16">
                    <div class="grid_3 omega">
                        <div class="icon"><i class="icon-laptop"></i></div>
                    </div>
                    <div class="grid_13 omega">
                        <div class="info-text"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sale_divider')->toHtml(); ?> </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
    <section class="widget-sale-products">



        <div class="container_16">
            <div class="section-heading">
                <div class="grid_5 alpha">
                    &nbsp;
                </div>
                <div class="grid_6">
                    <h2><?php echo $this->__('Best Sellers') ?></h2>
                    <div class="dot-divider"></div>
                    <div><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getStaticBlock())->toHtml(); ?></div>
                </div>
                <div class="grid_5 alpha">
                    &nbsp;
                </div>
            </div>

            <div class="grid_2 omega">
                <?php if ($collection->getSize() >1): ?>
                    <div class="navigation-buttons">
                        <span class="button scroll-left"></span>
                    </div>
                <?php endif; ?>
            </div>
            <div class="grid_12 alpha omega">
                <div class="block-content iosSlider-saleproducts">
                    <ul class="slider-items bigslider">
                        <?php foreach ($collection as $_product): ?>
                            <li class="item">
                                <div class="product-item">

                                    <?php
                                        $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                                        $_image = null;
                                        if (count($_gallery)) {
                                            foreach ($_gallery as $item)
                                            {
                                                $_image = $item->getFile();
                                            }
                                        }
                                    ?>

                                    <div class="grid_7 omega">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(470,null); ?>"
                                                 alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />

                                            <img class="hover-image"
                                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image',$_image)->keepFrame(false)->resize(470,null); ?>"
                                                 alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />

                                        </a>
                                        <div class="promo-container">
                                            <?php
                                            $_promo = $this->helper('sixtyone/data')->getPromoLabels($_product);
                                            echo $_promo['sale'];
                                            echo $_promo['new'];
                                            ?>
                                        </div>
                                    </div>

                                    <div class="grid_4 alpha ">




                                        <h2 class="item fn product-name">
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                        </h2>
                                        <p class="short-description"><?php echo substr($_product->getShortDescription(), 0,150);?></p>
                                        <?php if($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php endif; ?>
                                        <div class="price-box pricerange">
                                            <span class="price"><?php echo $_currency; ?><?php echo number_format($_product->getFinalPrice(),2); ?></span>
                                        </div>
                                        <div class="center">
                                            <a href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');" class="btn-cart btn-cart-icon">#</a>
                                        </div>
                                    </div>


                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="grid_2 alpha">
                <?php if ($collection->getSize() >1): ?>
                    <div class="navigation-buttons left">
                        <span class="button scroll-right"></span>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </section>
</div>
<?php endif ?>

