<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>
    <div class="cart-content grid_4 alpha omega">
        <?php $_cartQty = $this->getSummaryCount() ?>
        <?php if ($_cartQty>0): ?>
            <?php if ($_cartQty==1): ?>
                <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
            <?php else: ?>
                <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
            <?php endif ?>
        <?php endif ?>

        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)): ?>
            <ol id="cart-sidebar" class="mini-products-list">
            <?php foreach($_items as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
            
            <?php if ($_cartQty>0): ?>
                    <p class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                            <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                        <?php else: ?>
                            <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> 
                                <span class="subtotal-sum"><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></span>
                            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                                <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                            <?php endif; ?>
                        <?php endif; ?>
                    </p>
            <?php endif ?>            
            
        <?php else: ?>
            <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        <?php endif ?>
            
        <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
            <div class="actions">
                <?php echo $this->getChildHtml('extra_actions') ?>
                <button type="button" title="<?php echo $this->__('Continue To Checkout') ?>" class="button view-cart" onclick="setLocation('<?php echo $this->getUrl('checkout/cart')?>')"><span><span><?php echo $this->__('Continue To Checkout') ?></span></span><i class="icon-credit-card"></i></button>
            </div>
        <?php endif ?>            
    </div>
<?php endif;?>
