<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<div class="nav-container">
    <div id="main">
        <ul id="tabs_example_one" class="subsection_tabs">  
            <?php echo $this->drawTabsTabs(); ?>
        </ul>  
        <?php echo $this->drawTabsTabItems(); ?>

    </div>	
</div>

<?php echo $this->drawTabsJs(); ?>


