<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php $_productCollection = $this->getProductCollection(); ?>
<?php $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
	<?php echo $this->__('There are no products matching the selection.') ?>
<?php else: ?>
	<?php foreach ($_productCollection as $_product) { ?>
	
		<ul class="pop_item">
			<li class="image"><a title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(32, 32); ?>" alt="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" width="32" height="32" /></a></li>
			<li class="title"><a title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></li>
		</ul>
		
	<?php } ?>
<?php endif;?>