<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>

    <p class="block-subtitle"><?php echo $this->__('Last Added Items') ?></p>
    <?php if ($this->hasWishlistItems()): ?>
    <ol class="mini-products-list" id="wishlist-sidebar">
     <?php foreach ($this->getWishlistItems() as $_item): ?>
        <?php $product = $_item->getProduct(); ?>
        <li class="item">
            <a href="<?php echo $this->getProductUrl($_item) ?>" 
               title="<?php echo $this->escapeHtml($product->getName()) ?>" 
               class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(50,60); ?>"
                                                                                                                                                         alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
            <div class="product-details">
                <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?>');" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></p>
                <?php echo $this->getPriceHtml($product, false, '-wishlist') ?>
                <?php if ($product->isSaleable() && $product->isVisibleInSiteVisibility()): ?>
                    
                <a href="<?php echo $this->getItemAddToCartUrl($_item) ?>" 
                   class="link-cart"><?php echo $this->__('Add to Cart') ?>
                </a>
                
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('wishlist-sidebar');</script>
    <div class="actions">
        <button type="button" title="<?php echo $this->__('Wishlist') ?>" class="button view-wishlist" onclick="setLocation('<?php echo $this->helper('wishlist')->getListUrl() ?>')"><span><span><?php echo $this->__('Go to Wishlist') ?></span></span></button>
    </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
    <?php endif ?>

<?php endif ?>