<?php
/**
 * Magento
 *
 * @category    design
 * @package     sixtyone_default
 * @copyright   Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 */
/* @var $this Mage_Reports_Block_Product_Compared */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<section class="block-list block-compared">
    <header>
        <h2><?php echo $this->__('Recently Compared Products') ?></h2>
    </header>
    <div class="block-content">
        <ol id="recently-compared-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-compared-items');</script>
    </div>
</section>
<?php endif; ?>
