<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php if($this->canShowBlock()): ?>
    <div class="grid_16 alpha omega filters-bg-lines width-mobile">
        <section class="category-filters">
            <div id="filter-json-temp" style="display:none;"> </div>
            <div class="block-layered-nav">
                <div class="block-content">

                    <div class="grid_12 width-mobile alpha">
                        <div class="filter-list">
                            <?php if($this->canShowOptions()): ?>
                                <dl id="narrow-by-list">
                                    <?php $_filters = $this->getFilters() ?>
                                    <?php foreach ($_filters as $_filter): ?>
                                        <?php if($_filter->getItemsCount()): ?>
                                            <div class="filter-section">
                                                <dt class="block-options-heading" ><?php echo $this->__($_filter->getName()) ?></dt>
                                                <dd><?php echo $_filter->getHtml() ?></dd>
                                            </div>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="grid_4 width-mobile alpha omega ">
                        <?php
                                $state = $this->getStateHtml();
                                if ($state) {
                                   echo $this->getStateHtml();
                                } else {
                                   echo '<div class="no-filters"><span>'.$this->__('Select Something!').'</span><br/><i class="icon-hand-left"></i> </div>';
                                }
                        ?>
                    </div>
                </div>
            </div>
        </section>
    </div>
<?php endif; ?>
