<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">

    <div class="section-heading">
        <div class="grid_5 alpha">
            &nbsp;
        </div>
        <div class="grid_6">
            <h2><?php echo $this->__('Items In Your Shopping Cart') ?></h2>
            <div class="dot-divider"></div>
            <p><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_heading')->toHtml(); ?></p>
        </div>
        <div class="grid_5 alpha">
            &nbsp;
        </div>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <div class="table-wrapper">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <fieldset>
                <table id="shopping-cart-table" class="data-table cart-table">
                    <col width="1" />
                    <col />
                    <col width="1" />
                <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                <?php endif ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                    <col width="1" />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                    <col width="1" />

                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                        <tr>
                            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                            <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                            <th rowspan="<?php echo $mergedCells; ?>"></th>
                            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                            <?php endif ?>
                            <th class="a-center hide-mobile " colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="hide-mobile a-center"><?php echo $this->__('Qty') ?></th>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
                        </tr>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                        <?php endif; ?>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="50" class="a-right">
                                <div class="cart-footer-border"></div>
                                <?php if($this->getContinueShoppingUrl()): ?>
                                    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?><i class="icon-play"></i></span></span></button>
                                <?php endif; ?>
                                <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?><i class="icon-play"></i></span></span></button>
                                <!--[if lt IE 8]>
                                <input type="hidden" id="update_cart_action_container" />
                                <script type="text/javascript">
                                //<![CDATA[
                                    Event.observe(window, 'load', function()
                                    {
                                        // Internet Explorer (lt 8) does not support value attribute in button elements
                                        $emptyCartButton = $('empty_cart_button');
                                        $cartActionContainer = $('update_cart_action_container');
                                        if ($emptyCartButton && $cartActionContainer) {
                                            Event.observe($emptyCartButton, 'click', function()
                                            {
                                                $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                                $cartActionContainer.setAttribute('name', 'update_cart_action');
                                                $cartActionContainer.setValue('empty_cart');
                                            });
                                        }

                                    });
                                //]]>
                                </script>
                                <![endif]-->
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            </fieldset>
        </form>
    </div>
    <div class="cart-collaterals width-mobile">
        <div class="grid_10 alpha width-mobile">
            <div class="grid_5 alpha width-mobile">
                <div class="discount-container">

                <?php echo $this->getChildHtml('coupon') ?>
                </div>
            </div>
            <div class="grid_5 omega width-mobile">
                <div class="shipping-container">
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
                </div>
            </div>
        </div>
        <div class="totals-container grid_6 omega width-mobile">
            <div class="totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
            </div>

        </div>
    </div>
</div>

<?php echo $this->getChildHtml('crosssell') ?>