<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<div class="opc-checkout-page">

    <div class="checkout-header grid_8">
        <h2><?php echo $this->__('PLACE YOUR ORDER') ?></h2>
        <p><?php echo $this->__('Follow our easy steps to submit your order.') ?></p>
    </div>
    
    <article class="opc-container grid_11 omega">

        <div class="page-title">
            <h1><?php echo $this->__('Checkout') ?></h1>
        </div>
        <script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
        <ol class="opc" id="checkoutSteps">
        <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
            <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                <div class="step-title">
                    <span class="number"><?php echo $i ?></span>
                    <h2><?php echo $_stepInfo['label'] ?></h2>
                    <a href="#"><?php echo $this->__('Edit') ?></a>
                </div>
                <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                    <?php echo $this->getChildHtml($_stepId) ?>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">
        //<![CDATA[
            var accordion = new Accordion('checkoutSteps', '.step-title', true);
            <?php if($this->getActiveStep()): ?>
            accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
            <?php endif ?>
            var checkout = new Checkout(accordion,{
                progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
                review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
                saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
                failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
            );
        //]]>
        </script>
    </article>
    <aside class="opc-progress-container grid_4">
        <?php echo $this->getChildHtml('checkout.progress.wrapper') ?>
    </aside>
</div>