<?php
/**
 *
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if ($this->getCollection()->getSize()): ?>
        <div class="toolbar-wrapper">
            <div class="toolbar">
                    <?php if ($this->isEnabledViewSwitcher()): ?>
                        <div class="view-mode ">
                            <?php $_modes = $this->getModes(); ?>
                            <?php if ($_modes && count($_modes) > 1): ?>
                                <?php foreach ($this->getModes() as $_code => $_label): ?>
                                    <?php if ($this->isModeActive($_code)): ?>
                                        <strong title="<?php echo $_label ?>"
                                                class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                                    <?php else: ?>
                                        <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>"
                                           class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>


                    <div class="pager ">
                        <!--        <div class="amount">
                        <?php if($this->getLastPageNum()>1): ?>
                            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                        <?php else: ?>
                            <?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?>
                        <?php endif; ?>
                    </div>-->
                        <?php echo $this->getPagerHtml() ?>
                    </div>

                    <?php if ($this->isExpanded()): ?>
                        <div class="sorter">

                            <div class="limiter">
                                <label><?php echo $this->__('Show') ?>:</label>

                                <div class="form-limiter dropdown-container">
                                <span>
                                    <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
                                        <?php if ($this->isLimitCurrent($_key)): ?>
                                            <span class="current"><?php echo $_limit ?></span>
                                        <?php endif ?>
                                    <?php endforeach; ?>
                                </span>

                                    <div class="dropdown-content">
                                        <ul>
                                            <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
                                                <?php //$limiturl = str_replace("?", "#", $this->getLimitUrl($_key)); ?>
                                                <li>
                                                    <a href="<?php echo $this->getLimitUrl($_key); ?>"><?php echo $_limit ?> </a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="sort-by">
                                <label><?php echo $this->__('Sort By') ?>:</label>

                                <div class="form-sorter dropdown-container">
                                <span>
                                    <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
                                        <?php if ($this->isOrderCurrent($_key)): ?>
                                            <span class="current"><?php echo $this->__($_order) ?></span>
                                        <?php endif ?>
                                    <?php endforeach; ?>
                                </span>

                                    <div class="dropdown-content">
                                        <ul>
                                            <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
                                                <?php //$orderurl = str_replace("?", "#", $this->getOrderUrl($_key, 'asc')); ?>
                                                <li>
                                                    <a href="<?php echo $this->getOrderUrl($_key, 'asc'); ?>"><?php echo $_order ?> </a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                                <div class="order-direction">
                                    <?php if ($this->getCurrentDirection() == 'desc'): ?>
                                        <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>"
                                           title="<?php echo $this->__('Set Ascending Direction') ?>"><img
                                                src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>"
                                                alt="<?php echo $this->__('Set Ascending Direction') ?>"
                                                class="v-middle"/></a>
                                    <?php else: ?>
                                        <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>"
                                           title="<?php echo $this->__('Set Descending Direction') ?>"><img
                                                src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>"
                                                alt="<?php echo $this->__('Set Descending Direction') ?>"
                                                class="v-middle"/></a>
                                    <?php endif; ?>
                                </div>
                            </div>

                        </div>
                    <?php endif; ?>
            </div>
        </div>
<?php endif ?>
