<?php
/**
 * 
 * @category  design
 * @package   sixtyone_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php $upsell_count = count($this->getItemCollection()->getItems()); ?>
<?php if($upsell_count): ?>

<div class="section-heading">
    <div class="grid_5 alpha">
        &nbsp;
    </div>
    <div class="grid_6">
        <h2><?php echo $this->__('Upsell Products') ?></h2>
        <div class="dot-divider"></div>
        <p><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_upsell')->toHtml(); ?></p>
    </div>
    <div class="grid_5 alpha">
        &nbsp;
    </div>
</div>
<br class="clear">
<section class="box-collateral box-up-sell">
    
    <div class="grid_2 omega">
            <div class="navigation-buttons">
                <?php if ($upsell_count >3): ?>
                    <span class="button scroll-left"></span>
                <?php endif; ?>
            </div>
    </div>

    
    <div class="grid_12">
        <div id="upsell-container" class="iosSlider-upsell">
            <ul class="slider-items">
                <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
                <?php $this->resetItemsIterator() ?>
                <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                        <?php if($_product=$this->getIterableItem()): ?>
                            <li class="item">                
                                <div class="product-item">      
                                    
                                    <?php 
                                        $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                                        $_image = null;
                                        if (count($_gallery)) {
                                            foreach ($_gallery as $item)
                                            {
                                                $_image = $item->getFile();
                                            }     
                                        }
                                    ?>                                    
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(260,320) ?>"
                                             alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                        <img class="hover-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image',$_image)->resize(260,320) ?>"
                                             alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                    </a>



                                    <div class="promo-container">
                                        <?php 
                                            $_promo = $this->helper('sixtyone/data')->getPromoLabels($_product);
                                            echo $_promo['sale'];                        
                                            echo $_promo['new'];                        
                                        ?>   
                                    </div>

                                    <h2 class="item fn product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                    </h2>
                                    <p class="short-description"><?php echo substr($_product->getShortDescription(), 0,150);?></p>
                                    <?php if($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif; ?>
                                    <div class="price-box pricerange">
                                        <span class="price"><?php echo $_currency; ?><?php echo number_format($_product->getFinalPrice(),2); ?></span>
                                    </div>
                                    <div class="center">
                                        <a href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');" class="btn-cart btn-cart-icon">#</a>
                                    </div>


                                </div> 
                            </li>                        
                        <?php endif ?>     
                    <?php endfor; ?>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
    <div class="grid_2 alpha">
        <div class="navigation-buttons left">
            <?php if ($upsell_count >3): ?>
                <span class="button scroll-right"></span>
            <?php endif; ?>
        </div>
    </div>
</section>
<?php endif ?>
